### PR TITLE
remove windows macos linux directory

### PR DESCRIPTION
**Pull request by NIZE0000**
Remove necessary directories

### CODE REVIEW

**Comment by kaosittikorn** [comment]
So good

**Review by kaosittikorn — COMMENTED** [review]
so good

**Comment by NIZE0000** [comment]
Just merge fuck

**Comment by kaosittikorn** [comment]
can not merge fuck

**Review by kaosittikorn — COMMENTED** [review]
beautiful coding ever I have seen

**Review by kaosittikorn — APPROVED** [review]
beautiful coding I have seen

**Pull request merged**
